camera = camera_create();
Width = 320;
Height = 288;
var vm = matrix_build_lookat(x, y, -10, x, y, 0, 0, 1, 0);
var pm = matrix_build_projection_ortho(Width, Height, 1, 10000000);
camera_set_view_mat(camera, vm);
camera_set_proj_mat(camera, pm);
view_camera[0] = camera;
camera_apply(camera);
window_set_size(Width, Height);
Paused = false;
