ArmSquish = 20;
SwingTimer = 0;
BounceFrame = 900;
HeadState = 1;
Timer = 0;
Mode = "Idle";
ReturnDegree = 1;
Aggro = 0;
Height = -600;
Angle = 0;
LookedAt = 0;
Side = random_sign();
RandomValue = random_range(0.8, 1.2);
audio_sound_gain(sfxNightmarionneGarble, 0, 0);
Head = undefined;
