var ScaleSize = 0.5;
var x1 = x + ((sprite_width / 2) * dcos(image_angle) * ScaleSize);
var y1 = y + ((sprite_width / 2) * dsin(image_angle) * ScaleSize);
var x2 = x - ((sprite_width / 2) * dcos(image_angle) * ScaleSize);
var y2 = y - ((sprite_width / 2) * dsin(image_angle) * ScaleSize);
var zTop = 256 + (256 * ScaleSize);
var zBottom = 256 - (256 * ScaleSize);
var TextureWidth = 1;
shader_set(TransparencyShader);
var Texture = sprite_get_texture(sMazeTex_Wood, 0);
VertexBuffer = vertex_create_buffer();
vertex_begin(VertexBuffer, global.VertexFormat);
vertex_set_point(VertexBuffer, x1, y1, zTop, 0, 0);
vertex_set_point(VertexBuffer, x2, y2, zBottom, TextureWidth, 1);
vertex_set_point(VertexBuffer, x1, y1, zBottom, 0, 1);
vertex_set_point(VertexBuffer, x1, y1, zTop, 0, 0);
vertex_set_point(VertexBuffer, x2, y2, zBottom, TextureWidth, 1);
vertex_set_point(VertexBuffer, x2, y2, zTop, TextureWidth, 0);
vertex_end(VertexBuffer);
vertex_submit(VertexBuffer, pr_trianglelist, Texture);
vertex_delete_buffer(VertexBuffer);
shader_reset();
Frame += 1;
image_angle = Frame;
x = oCamera.x + lengthdir_y(128, image_angle + 180);
y = oCamera.y + lengthdir_x(128, image_angle + 180);
