audio_group_load(voc_ToyFreddy_HardlyGaming);
BodyY = 160;
BodyYSpeed = 0;
BodyYTarget = BodyY;
BodyYSnappiness = 0.5;
BodyYBounce = 0.2;
BodyAngle = 75;
BodyAngleSpeed = 0;
BodyAngleTarget = BodyAngle;
BodyAngleSnappiness = BodyYSnappiness;
BodyAngleBounce = BodyYBounce;
BodyImage = -1;
CurrentBodyImage = BodyImage;
HeadY = 0;
HeadYSpeed = 0;
HeadYTarget = HeadY;
HeadYSnappiness = 0.5;
HeadYBounce = 0.2;
HeadAngle = 90;
HeadAngleSpeed = 0;
HeadAngleTarget = HeadAngle;
HeadAngleSnappiness = HeadYSnappiness;
HeadAngleBounce = HeadYBounce;
HeadImage = -2;
CurrentHeadImage = HeadImage;
SequenceStep = 0;
NextPoint = 9.8;
SoundQueue = [voc_Salvage_Ending1];
SoundQueuePos = 0;
SoundPlaying = -1;
SubtitleQueue = [[""], [0]];
CurrentSubtitleLine = 0;
Frame = 0;
PostVoiceTimer = 0;
BodyYTarget = 8;
BodyY = BodyYTarget;
BodyAngleTarget = 0;
BodyAngle = 0;
BodyAngleSnappiness = 0.8;
HeadAngleTarget = 0;
HeadAngle = 0;
HeadAngleSnappiness = 0.8;
HeadYTarget = 24;
HeadY = 24;
HeadImage = 4;
BodyImage = 0;
CurrentHeadImage = HeadImage;
CurrentBodyImage = BodyImage;
FistX = 352;
FistXTarget = 352;
FistY = 350;
FistYTarget = 350;
FistSize = 0.9;
FistSizeTarget = 0.75;
FistSizeSpeed = 0;
FistSnappiness = 0.15;
Fist = instance_create_layer(0, 0, "Behind_Wall", oOfficeSprite);
Head = instance_create_layer(0, 0, "Behind_Wall", oOfficeSprite);
Body = instance_create_layer(0, 0, "Behind_Wall", oOfficeSprite);
Glass = -1;
Delay = 180;
FistTimer = 0;
audio_stop_all();

with (oCamera)
{
    force_mask_off();
    reverb_sound(sfxMetalImpact, 0, 0, false, 1.2);
    reverb_sound(voc_Salvage_FinalHit, 0, 0, false, 1.2);
}

instance_destroy(oAnimatronicParent);
