PhoneActive = 0;
PhoneButtonX = 320;
PhoneButtonY = 360;
ButtonWidth = 80;
ButtonHeight = 24;
CurrentSubtitleLine = 0;
PhoneCalls = [vocPhoneGuy1, vocPhoneGuy2, vocPhoneGuy3, vocPhoneGuy4, vocPhoneGuy5, vocPhoneGuy6];

if (is_numeric(global.Night) && !global.CallMuted)
    TonightsCall = PhoneCalls[global.Night - 1];
else
    TonightsCall = undefined;

TonightsCallPlaying = TonightsCall;
global.PhoneGuySubtitles = [];

function add_subtitle_line(arg0, arg1, arg2, arg3)
{
    global.PhoneGuySubtitles[arg0][array_length(global.PhoneGuySubtitles[arg0])] = 
    {
        Text: arg1,
        Time: (arg2 * 60) + arg3
    };
}

add_subtitle_line(1, "...Hello? Hello hello?", 0, 0);
add_subtitle_line(1, "Hey, I hope this message finds you well!", 0, 2);
add_subtitle_line(1, "Now I've got a salvaging job in the morning, and I imagine you got a looong night ahead of you,", 0, 4.5);
add_subtitle_line(1, "Sooo, for the both of our sakes, I'll try to make this brief.", 0, 9.3);
add_subtitle_line(1, "First and foremost: Your job!", 0, 12.9);
add_subtitle_line(1, "I'm sure your manager already went over this, but...wouldn't hurt to cover it again.", 0, 14.9);
add_subtitle_line(1, "So you, as the night watchman here, have two duties:", 0, 19.1);
add_subtitle_line(1, "Keeping intruders out, and keeping all our equipment in here safe...", 0, 22.4);
add_subtitle_line(1, "Most notable of which being, of course, being our animatronic band!", 0, 26.3);
add_subtitle_line(1, "Y'see the animatronic characters here...you may notice they tend to move around at night.", 0, 30.2);
add_subtitle_line(1, "DON'T FRET - It's completely normal! Even animatronics need their exercise.", 0, 34.9);
add_subtitle_line(1, "Stops their mechanisms from locking up when they need to perform in the morning, and saves our maintenance crew a looot of hassle.", 0, 38.8);
add_subtitle_line(1, "Now, that normally wouldn't be an issue for you, but our animatronics...", 0, 45.1);
add_subtitle_line(1, "Well...they also have a tendency to wander to parts of the building they aren't supposed to be in...", 0, 49.4);
add_subtitle_line(1, "...Which might also include your office.", 0, 53.8);
add_subtitle_line(1, "Because of that, you'll wanna keep an eye on them with your cameras,", 0, 56.1);
add_subtitle_line(1, "just make sure they aren't straying too far away from their intended areas.", 0, 59.2);
add_subtitle_line(1, "Oh, and if one reaches the doorway to your office,", 1, 3.1);
add_subtitle_line(1, "it might be a good idea to close either of those handy mechanical doors.", 1, 5.5);
add_subtitle_line(1, "There should be one on both sides of your office.", 1, 9.1);
add_subtitle_line(1, "They stop almost any animatronic.", 1, 11.5);
add_subtitle_line(1, "Just close 'em, wait for the 'THUNK!'...", 1, 13.9);
add_subtitle_line(1, "...And the animatronic should go right back to their stage.", 1, 15.9);
add_subtitle_line(1, "Only close them if you absolutely NEED to, though,", 1, 18.6);
add_subtitle_line(1, "the doors drain power and power isn't something you've got a lot of.", 1, 20.6);
add_subtitle_line(1, "And I say ALMOST every animatronic because there IS one that's a little special, though it isn't hard to deal with.", 1, 24.4);
add_subtitle_line(1, "Just click that 'Reset Music' button on the entrance camera every once in a while and it should leave you be.", 1, 30.8);
add_subtitle_line(1, "Now if you're wondering why a place like this needs heavy duty mechanical doors,", 1, 36.1);
add_subtitle_line(1, "or what all these others tools you have at your disposal are,", 1, 39.4);
add_subtitle_line(1, "my answer to both of these questions is:", 1, 41.9);
add_subtitle_line(1, "Don't worry about it! You probably won't need to use 'em tonight anyway.", 1, 43.7);
add_subtitle_line(1, "We just wanna make sure our guards are safe and have the means to defend themselves against any threat that comes their way!", 1, 47.4);
add_subtitle_line(1, "...Like, y'know. Burglars. Vandals. Those kinds of threats.", 1, 53.7);
add_subtitle_line(1, "Other than that, the only thing you really have to worry about is your temperature!", 1, 59.1);
add_subtitle_line(1, "The AC's shot, so you'll have to rely on your fan.", 2, 2.3);
add_subtitle_line(1, "Just turn it on every so often, it should cool you right back down.", 2, 5.1);
add_subtitle_line(1, "Just don't leave it on for TOO long, it drains power too.", 2, 8.3);
add_subtitle_line(1, "Oh yeah, and while all you SHOULD really need tonight are the cameras and doors,", 2, 11.6);
add_subtitle_line(1, "feel free to flip through the different systems on your monitor and try out some of the other tools just to get a feel for them too.", 2, 15.8);
add_subtitle_line(1, "It doesn't hurt to be prepared!", 2, 21.8);
add_subtitle_line(1, "Now I think that's everything...unless I'm forgetting about something...", 2, 23.9);
add_subtitle_line(1, "No no! I'm sure that's-", 2, 30.9);
add_subtitle_line(1, "What the!?", 2, 33.6);
add_subtitle_line(1, "*CRASH!*", 2, 33.8);
add_subtitle_line(2, "And that should be-", 0, 0);
add_subtitle_line(2, "...Yep! Okay, uh...Hi! Hi, uh...sorry.", 0, 1);
add_subtitle_line(2, "The guy that called you last night can't QUITE get back to you, he got into a pretty...", 0, 3.6);
add_subtitle_line(2, "...Nasty accident with the office locker right when he finished recording your message.", 0, 7.2);
add_subtitle_line(2, "Apparently the animatronics filled it with the heaviest stuff they could find, and the thing just...", 0, 11.7);
add_subtitle_line(2, "...tipped over right onto him.", 0, 16.3);
add_subtitle_line(2, "It's...it's still lying there.", 0, 18.5);
add_subtitle_line(2, "...I think he still might be in it, actually.", 0, 21);
add_subtitle_line(2, "...", 0, 23.3);
add_subtitle_line(2, "I have no idea where they managed to find that many blocks of pure tungsten, but...", 0, 24.2);
add_subtitle_line(2, "You know Freddy and the gang! They're...some real kidders, heh.", 0, 29);
add_subtitle_line(2, "...That aside, I heard you made some salvages last night. That's good! That's good.", 0, 33.8);
add_subtitle_line(2, "I don't really know...how those ones work, not my jurisdiction...", 0, 37.3);
add_subtitle_line(2, "So I guess it's up to you to figure that out.", 0, 40.5);
add_subtitle_line(2, "Other than that, we've been noticing some...STRANGE new behaviors with some of the animatronics.", 0, 42.3);
add_subtitle_line(2, "Namely, uh...they REALLY like getting into our vent system now.", 0, 47.2);
add_subtitle_line(2, "If you switch to the 'Vents' setting on your monitor and see one just, crawling around up there...", 0, 51.3);
add_subtitle_line(2, "...It MIGHT be a good idea to set an audio lure nearby to pull it away from your office.", 0, 55.1);
add_subtitle_line(2, "Now, if one DOES get into your office, don't worry, just...", 0, 59.4);
add_subtitle_line(2, "Try throwing on that spare Freddy head for a bit until they go away.", 1, 2.5);
add_subtitle_line(2, "Usually fools them pretty easily.", 1, 6.6);
add_subtitle_line(2, "And that should be it...?", 1, 8.2);
add_subtitle_line(2, "I'm actually coming up at the end of my shift here, SO...", 1, 10.9);
add_subtitle_line(2, "If you'll excuse me, I'm gonna recklessly meander my way over towards the exit door and-", 1, 14.2);
add_subtitle_line(2, "*THUNK*", 1, 18.8);
add_subtitle_line(3, "Hey, welcome back!", 0, 0);
add_subtitle_line(3, "...Um, right. Sorry about the background noise.", 0, 2.7);
add_subtitle_line(3, "I didn't wanna end up like the last guy...", 0, 6.1);
add_subtitle_line(3, "...so I decided to hide out in the women's restroom!", 0, 9);
add_subtitle_line(3, "But, as it turns out...", 0, 11.5);
add_subtitle_line(3, "...Freddy does his singing practice in here, so...", 0, 13.6);
add_subtitle_line(3, "Just...just try to ignore him.", 0, 16.5);
add_subtitle_line(3, "Uh, anyway...", 0, 19.2);
add_subtitle_line(3, "Have you checked out the game menu?", 0, 20.1);
add_subtitle_line(3, "You can play a bunch of dumb little minigames in there.", 0, 22.2);
add_subtitle_line(3, "You can even earn tokens for it too! The boss set it up.", 0, 24.5);
add_subtitle_line(3, "I...think he wants to give us an incentive to playtest his...microgames or something?", 0, 27.4);
add_subtitle_line(3, "I-I dunno, but you can ignore it if you need to focus on your job.", 0, 31.8);
add_subtitle_line(3, "Oh, and you can spend those tokens you get in the shop menu.", 0, 34.7);
add_subtitle_line(3, "Give it a look when you get the chance! There's a BUNCH of useful stuff in there.", 0, 37.2);
add_subtitle_line(3, "Uh, anyway, I'll get back to you tomorrow, I should-", 0, 40.3);
add_subtitle_line(3, "Ohhhh...", 0, 43.7);
add_subtitle_line(3, "Could you KEEP IT DOWN IN THERE!?", 0, 44.5);
add_subtitle_line(3, "Wha-", 0, 48.4);
add_subtitle_line(3, "What'd you say to me?", 0, 49.3);
add_subtitle_line(3, "Um...", 0, 51.2);
add_subtitle_line(3, "W-Woah, hey, hey, I didn't mean to!", 0, 52.5);
add_subtitle_line(3, "Hey hey HEY HEY!", 0, 54);
add_subtitle_line(4, "Hey palie.", 0, 0);
add_subtitle_line(4, "Yeah, yeah you guessed it. The last guy was found dead again.", 0, 0.8);
add_subtitle_line(4, "Poor bastard fell victim to a lethal swirlie.", 0, 4.2);
add_subtitle_line(4, "Anyway.", 0, 8);
add_subtitle_line(4, "I don't really got any survival tips for you or anything,", 0, 9);
add_subtitle_line(4, "You seem to have it pretty much down by now, anyway...", 0, 11.5);
add_subtitle_line(4, "...Uh, but what I DO have...", 0, 13.8);
add_subtitle_line(4, "*COCKS GUN*", 0, 15.2);
add_subtitle_line(4, "...Is a GUN!", 0, 15.8);
add_subtitle_line(4, "And I ain't meeting the same fate as those shmucks before me!", 0, 17.1);
add_subtitle_line(4, "YOU HEAR THAT, YOU BEAR BASTARD!?", 0, 20.6);
add_subtitle_line(4, "YOU WANNA PIECE OF ME!?", 0, 22.7);
add_subtitle_line(4, "WELL COME GET SOME OF THIS!", 0, 24.4);
add_subtitle_line(5, "Hey, it's me again!", 0, 0);
add_subtitle_line(5, "Congratulations on making it to the end of the week.", 0, 1.5);
add_subtitle_line(5, "You seem real wise with the security stuff by now, so I'll just leave you to it.", 0, 4.2);
add_subtitle_line(5, "But, uh...", 0, 8.3);
add_subtitle_line(5, "Just don't forget to check out the shop and buy something if you find yourself struggling with anything.", 0, 8.8);
add_subtitle_line(5, "...Oh yeah.", 0, 14.1);
add_subtitle_line(5, "I actually did end up dying last night.", 0, 15);
add_subtitle_line(5, "The bullet ricocheted off of Freddy's head and right back into my skull.", 0, 17.1);
add_subtitle_line(5, "...So...my soul is trapped inside this phone now.", 0, 22.2);
add_subtitle_line(5, "...", 0, 26.3);
add_subtitle_line(5, "...You uh...you have fun with your last shift.", 0, 28.4);
add_subtitle_line(6, "Hey, chump! It's-a me!", 0, 0);
add_subtitle_line(6, "...Your boss.", 0, 2.4);
add_subtitle_line(6, "Now, keep an eye on those bots, eh?", 0, 3.5);
add_subtitle_line(6, "They're shiny, and worth a LOT of gold coins, eheheheheh...", 0, 5.9);
add_subtitle_line(6, "...But they're also some real jerks!", 0, 10.1);
add_subtitle_line(6, "...And I already made a reservation at the steakhouse, so you better make it out of there in one piece!", 0, 12.3);
add_subtitle_line(6, "Don't be a stooge, and uh...", 0, 18.1);
add_subtitle_line(6, "Have a rotten night! Wahahahaha!", 0, 20.3);
add_subtitle_line(6, "*BLOWS RASPBERRY*", 0, 23.3);
Timer = 0;
depth = 100;
