DrawDepth = 0;
YOffset = 0;
YSpeed = 0;
Active = true;
Size = 1;
KillFrames = 0;
Side = random_sign();
Difficulty = oFredbear.Difficulty;
TimeUntilKill = lerp(10, 7, Difficulty);
simple_sound(sfxFredbearDoor, Side * 400, 0, false);
Frame = 0;
Face = instance_create_layer(0, 0, "Behind_Wall", oOfficeSprite);
