ShockTimer = 0;
PoweroutTimer = 0;
audio_play_sound(sfxSalvageClatter, 15, false);
Active = true;
CurrentCam = 99;
PossibleCams = array_shuffle([1, 2, 3, 4, 5, 6, 7, 8]);
CamSwitchesToFind = 3;
KillTimer = lerp(15, 10, oFredbear.Difficulty);
audio_sound_gain(sfxFredbearGarble, 0, 0);
audio_play_sound(sfxFredbearGarble, 15, true);
